//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfWebClient.CourseReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Courses", Namespace="http://schemas.datacontract.org/2004/07/WCFDemo.Services")]
    [System.SerializableAttribute()]
    public partial class Courses : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreditsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((this.CourseIDField.Equals(value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Credits {
            get {
                return this.CreditsField;
            }
            set {
                if ((this.CreditsField.Equals(value) != true)) {
                    this.CreditsField = value;
                    this.RaisePropertyChanged("Credits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CourseReference.ICourseService")]
    public interface ICourseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetAll", ReplyAction="http://tempuri.org/ICourseService/GetAllResponse")]
        WcfWebClient.CourseReference.Courses[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetAll", ReplyAction="http://tempuri.org/ICourseService/GetAllResponse")]
        System.Threading.Tasks.Task<WcfWebClient.CourseReference.Courses[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/Get", ReplyAction="http://tempuri.org/ICourseService/GetResponse")]
        WcfWebClient.CourseReference.Courses Get(int CourseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/Get", ReplyAction="http://tempuri.org/ICourseService/GetResponse")]
        System.Threading.Tasks.Task<WcfWebClient.CourseReference.Courses> GetAsync(int CourseID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/Update", ReplyAction="http://tempuri.org/ICourseService/UpdateResponse")]
        WcfWebClient.CourseReference.Courses Update(WcfWebClient.CourseReference.Courses item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/Update", ReplyAction="http://tempuri.org/ICourseService/UpdateResponse")]
        System.Threading.Tasks.Task<WcfWebClient.CourseReference.Courses> UpdateAsync(WcfWebClient.CourseReference.Courses item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/Add", ReplyAction="http://tempuri.org/ICourseService/AddResponse")]
        WcfWebClient.CourseReference.Courses Add(WcfWebClient.CourseReference.Courses item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/Add", ReplyAction="http://tempuri.org/ICourseService/AddResponse")]
        System.Threading.Tasks.Task<WcfWebClient.CourseReference.Courses> AddAsync(WcfWebClient.CourseReference.Courses item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICourseServiceChannel : WcfWebClient.CourseReference.ICourseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseServiceClient : System.ServiceModel.ClientBase<WcfWebClient.CourseReference.ICourseService>, WcfWebClient.CourseReference.ICourseService {
        
        public CourseServiceClient() {
        }
        
        public CourseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfWebClient.CourseReference.Courses[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<WcfWebClient.CourseReference.Courses[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public WcfWebClient.CourseReference.Courses Get(int CourseID) {
            return base.Channel.Get(CourseID);
        }
        
        public System.Threading.Tasks.Task<WcfWebClient.CourseReference.Courses> GetAsync(int CourseID) {
            return base.Channel.GetAsync(CourseID);
        }
        
        public WcfWebClient.CourseReference.Courses Update(WcfWebClient.CourseReference.Courses item) {
            return base.Channel.Update(item);
        }
        
        public System.Threading.Tasks.Task<WcfWebClient.CourseReference.Courses> UpdateAsync(WcfWebClient.CourseReference.Courses item) {
            return base.Channel.UpdateAsync(item);
        }
        
        public WcfWebClient.CourseReference.Courses Add(WcfWebClient.CourseReference.Courses item) {
            return base.Channel.Add(item);
        }
        
        public System.Threading.Tasks.Task<WcfWebClient.CourseReference.Courses> AddAsync(WcfWebClient.CourseReference.Courses item) {
            return base.Channel.AddAsync(item);
        }
    }
}
